image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - apk add git
  - set -x
  - source ci-utils/create_version_number.sh
  - 'env | sort'
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo building
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  artifacts:
    expire_in: 1 week
    paths:
      - .
